### ISSUE TITLE
Sample not working as expected

### ISSUE THREAD

**Issue by LMSSonos** [GoogleCloudPlatform/jobs-demos#14]
Hello

I'm trying to run the sample as described in https://github.com/GoogleCloudPlatform/jobs-demos/tree/main/screenshot - I encountered following issues

1) In the README the link to codelab is broken
2) If I run the Create cloud run job command from the README, I get following error: `ERROR: (gcloud.alpha.run.jobs.create) unrecognized arguments: --task-timeout=5m (did you mean '--http-timeout'?)` 
3) If I remove the `--task-timeout=5m`, I get the following error 
```ERROR: (gcloud.alpha.run.jobs.create) Namespaces instance [myproject] not found: Requested entity was not found.```

I was not able to solve the Namespace issue. Is there a additional required step which is missing?
Thanks

**Comment by meteatamel** [comment]
Hi @LMSSonos, is your project allow-listed for Cloud Run jobs?

**Comment by LMSSonos** [comment]
Hi @meteatamel - I updated to the latest SDK and the Namespaces issue disappeard. Don't know what the issue was.

```
Google Cloud SDK 383.0.1
alpha 2022.04.26
bq 2.0.74
core 2022.04.26
gsutil 5.9
```

Just to let you know, this is a awesome feature we will try to run some non critical production workloads with it.

**Comment by meteatamel** [comment]
Glad to know!
